# Positions and lengths in physical space are specified in metres, relative to the symmetry axis for R, and the Z=0 plane for Z
# Currents are in MA
# For typical numbers, copper coils can achieve 5 MA/m^2
# and superconducting Nb3Sn coil packs average 20 MA/m^2

[options]

# will generate helmholtz.vtk, helmholtz_psi.gf, helmholtz_grad_psi.gf
MeshFile = "helmholtz.vtk"
FinalMeshFile = "output_helmholtz.vtk"
PsiFile = "helmholtz_psi.gf"
GradPsiFile = "helmholtz_grad_psi.gf"

# Details of the solution domain
[domain]

# Boundaries of the domain
RMin = 0.001
RMax = 2.0
ZMin = -1.5
ZMax = 1.5

# Don't touch this
BoundaryCondition = "VonHagenow"

# Away from the coils, what is a reasonable guess at the 
# scale of psi variation. Used to generate initial mesh. 
# Refined Later.
CellSize = 0.1

# Coils is an array of tables
# just keep adding coils by adding entries.

# Just a helmholtz pair
[[coils]]
R = 1.0
Z = 0.5
Width = 0.1
Height = 0.1
Current = 1.0

[[coils]]
R = 1.0
Z = -0.5
Width = 0.1
Height = 0.1
Current = 1.0

