
/*
 * The Maryland Equilibrium Solver
 */

#include "mfem.hpp"

#include "meq.hpp"

#include <vector>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <algorithm>
#include <functional>


using namespace mfem;
using namespace meq;

int main(int argc, char *argv[])
{

	// Parse command-line options.
	int order = 3;
	int initial_ref_levels = 0;

	// TODO -- replace with boost option parser
	OptionsParser args(argc, argv);
	const char *config_file = "meq.conf";

   args.AddOption(&config_file, "-c", "--config",
                  "Config file to use.");
	args.AddOption(&order, "-o", "--order",
			"Finite element order (polynomial degree).");
	args.AddOption(&initial_ref_levels, "-mr", "--mesh-refinement-levels",
			"The number of levels of uniform refinement to apply to the grid.");
	args.Parse();
	if (!args.Good())
	{
		args.PrintUsage(std::cout);
		return 1;
	}

	std::shared_ptr<meq::Configuration> config = nullptr;

	try {
		config = std::make_shared<meq::Configuration>( config_file );
	} catch ( toml::syntax_error &tomlErr ) {
		
		std::cerr << "Error parsing the configuration in " << config_file << std::endl;
		std::cerr << tomlErr.what() << std::endl;
		return 2;
	} catch ( std::exception &other ) {
		std::cerr << "Unknown Error in loading configuration: " << other.what() << std::endl;
		return 3;
	}

	std::cout << "Using configuration in " << config_file << std::endl;
 
	// Should be generated by meshgen
	std::shared_ptr<Mesh> mesh = nullptr;
	try {
		mesh = std::make_shared<Mesh>( config->GetMeshFile().c_str() );
	} catch ( std::exception &e ) {
		std::cerr << "Unable to load the mesh from " << config->GetMeshFile() << "." << std::endl;
		std::cerr << " Error: " << e.what() << std::endl << std::endl;
		std::cerr << "Have you run MEQMeshGen ?" << std::endl;
		return -1;
	}

	for (int ii=0; ii<initial_ref_levels; ii++)
		mesh->UniformRefinement();

	std::cout << " Final Mesh for simulation contains " << mesh->GetNE() << " elements." << std::endl;

	// The RHS function is FieldCoils::operator()
	meq::Jtor FieldCoils;

	for ( const auto coil : config->GetCoils() )
		FieldCoils.AddCoil( coil );

	auto J_plasma = [ &FieldCoils ]( const mfem::Vector& pt, double psi ) {
		return FieldCoils( pt );
	};
	
	ConstantCoefficient zero( 0.0 );
	meq::GSSolver solver( mesh, order, J_plasma );

	std::cout << " Total Number of Degrees of Freedom for Psi      " << solver.USpace()->GetNDofs() << std::endl;
	std::cout << " Total Number of Degrees of Freedom for Grad Psi " << solver.QSpace()->GetNDofs() << std::endl;

	solver.SetBCs( zero );

	mfem::Vector qu_zero_bc;
	qu_zero_bc.SetSize( solver.Height() );
	qu_zero_bc = 0.0;
	solver.Mult( qu_zero_bc, qu_zero_bc );


	GreensFunctionBoundaryCoefficient Lackner( mesh.get(), solver.QSpace(), qu_zero_bc );

	mfem::Vector qu;
	solver.SetBCs( Lackner );
	qu.SetSize( solver.Height() );
	qu = 0.0;
	solver.Mult( qu, qu );

	GridFunction q_solution,u_solution;
	q_solution.MakeRef( solver.QSpace(), qu, 0 );
	u_solution.MakeRef( solver.USpace(), qu, solver.QSpace()->GetVSize() );

	// Save the output
	{

		std::ofstream mesh_ofs( config->GetFinalMeshFile() );
		mesh_ofs.precision(8);
		mesh->Print(mesh_ofs);

		std::ofstream q_solution_ofs( config->GetGradPsiFile() );
		q_solution_ofs.precision(8);
		q_solution.Save(q_solution_ofs);

		std::ofstream u_solution_ofs( config->GetPsiFile() );
		u_solution_ofs.precision(8);
		u_solution.Save(u_solution_ofs);

	}

	return 0;
}

