# Positions and lengths in physical space are specified in metres, relative to the symmetry axis for R, and the Z=0 plane for Z
# Currents are in MA
# For typical numbers, copper coils can achieve 5 MA/m^2
# and superconducting Nb3Sn coil packs average 20 MA/m^2

[options]

# will generate vacuum.vtk, vacuum_psi.gf, vacuum_grad_psi.gf
MeshFile = "vacuum.vtk"
OutputMeshFile = "output_vacuum.vtk"
PsiFile = "vacuum_psi.gf"
GradPsiFile = "vacuum_grad_psi.gf"

# Details of the solution domain
[domain]

# Boundaries of the domain
RMin = 0.01
RMax = 2.5
ZMin = -3.0
ZMax = 3.0

# Don't touch this
BoundaryCondition = "VonHagenow"

# Away from the coils, what is a reasonable guess at the 
# scale of psi variation. Used to generate initial mesh. 
# Refined Later.
PsiResolution = 0.25

# Coils is an array of tables
# just keep adding coil packs by adding entries.

[[coils]]
R = 0.65
Z = 2.0
Width = 0.2
Height = 0.2
Current = 4.25

[[coils]]
R = 0.65
Z = -2.0
Width = 0.2
Height = 0.2
Current = 4.25

[[coils]]
R = 1.5
Z = 1.1
Width = 0.2
Height = 0.2
Current = 0.5

[[coils]]
R = 1.5
Z = 0.4
Width = 0.2
Height = 0.2
Current = 0.5

[[coils]]
R = 1.5
Z = -1.1
Width = 0.2
Height = 0.2
Current = 0.5

[[coils]]
R = 1.5
Z = -0.4
Width = 0.2
Height = 0.2
Current = 0.5





