
/*
 * An MFEM-based nonlinear poisson solver, derived from the HDG Example Poisson Solver
 * of T. Horvath, S. Rhebergen, and A. Sivas.
 *
 * The discretization is based on the paper:
 * N.C. Nguyen, J. Peraire, B. Cockburn, An implicit high-order hybridizable
 * discontinuous Galerkin method for linear convection–diffusion equations,
 * J. Comput. Phys., 2009, 228:9, 3232--3254.
 *
 * Modifications are by I. G. Abel, University of Maryland
 */

#include "mfem.hpp"
#include "GSInverter.hpp"
#include "FreeBoundary.hpp"
#include "toml11/toml.hpp"
#include "meq.hpp"

#include <vector>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <algorithm>
#include <functional>


using namespace std;
using namespace mfem;

int main(int argc, char *argv[])
{

	// Parse command-line options.
	int order = 3;
	int initial_ref_levels = 0;

	// TODO -- replace with boost option parser
	OptionsParser args(argc, argv);
	const char *config_file = "meq.conf";

   args.AddOption(&config_file, "-c", "--config",
                  "Config file to use.");
	args.AddOption(&order, "-o", "--order",
			"Finite element order (polynomial degree).");
	args.AddOption(&initial_ref_levels, "-mr", "--mesh-refinement-levels",
			"The number of levels of uniform refinement to apply to the grid.");
	args.Parse();
	if (!args.Good())
	{
		args.PrintUsage(cout);
		return 1;
	}

	const auto config = toml::parse( config_file );
	const auto coils = toml::find< std::vector< toml::table > >( config, "coils" );
	const auto options = toml::find< toml::table >( config, "options" );

	std::string MeshFile;

	MeshFile = options.at( "MeshFile" ).as_string();

	Jtor FieldCoils;

	for ( const auto coil : coils )
	{
		double R = coil.at( "R" ).as_floating();
		double Z = coil.at( "Z" ).as_floating();
		double w = coil.at( "Width" ).as_floating();
		double h = coil.at( "Height" ).as_floating();
		double I = coil.at( "Current" ).as_floating();
		double coil_area = w*h;
		double j_coil = I/coil_area;
		FieldCoils.AddCoil( R, Z, h, w, j_coil );
	}

	

	// Should be generated by meshgen
	Mesh *mesh = new Mesh( MeshFile.c_str() );

	int dim = mesh->Dimension();

	for (int ii=0; ii<initial_ref_levels; ii++)
		mesh->UniformRefinement();

	// The RHS function is FieldCoils::operator()
	
	ConstantCoefficient zero( 0.0 );
	GSSolver solver( mesh, order, FieldCoils );
	solver.SetBCs( zero );

	mfem::Vector qu_zero_bc;
	solver.Solve( qu_zero_bc );


	// Boundary Values
	mfem::Vector r( 2 );
	std::cout << std::setprecision( 12 );

	r( 0 ) = 0.01; r( 1 ) = 0.0;
	std::cout << "Psi at (0.01, 0.00) = " << BoundaryPsi( solver.GetQSpace(), qu_zero_bc, r ) << std::endl;
	r( 0 ) = 0.01; r( 1 ) = 0.75;
	std::cout << "Psi at (0.01, 0.75) = " << BoundaryPsi( solver.GetQSpace(), qu_zero_bc, r ) << std::endl;
	r( 0 ) = 0.01; r( 1 ) = -0.75;
	std::cout << "Psi at (0.01,-0.75) = " << BoundaryPsi( solver.GetQSpace(), qu_zero_bc, r ) << std::endl;
	std::cout << std::endl;

	// Perform the Lackner trick to compute the boundary condition
	GreensFunctionBoundaryCoefficient Lackner( mesh, solver.GetQSpace(), qu_zero_bc );

	mfem::Vector qu;
	solver.SetBCs( Lackner );
	solver.Solve( qu );

	GridFunction q_solution,u_solution;
	q_solution.MakeRef( solver.GetQSpace(), qu, 0 );
	u_solution.MakeRef( solver.GetUSpace(), qu, solver.GetQSpace()->GetVSize() );

	mfem::DenseMatrix points( 2, 6 );
	points( 0, 0 ) = 0.5;
	points( 1, 0 ) = 0.0;
	points( 0, 1 ) = 0.5;
	points( 1, 1 ) = 0.5;
	points( 0, 2 ) = 0.5;
	points( 1, 2 ) = -0.5;

	points( 0, 3 ) = 0.75;
	points( 1, 3 ) = 0.0;
	points( 0, 4 ) = 0.75;
	points( 1, 4 ) = 0.75;
	points( 0, 5 ) = 0.75;
	points( 1, 5 ) = -0.75;

	mfem::Array<int> ids;
	mfem::Array<mfem::IntegrationPoint> ips;

	mesh->FindPoints( points, ids, ips );
	
	std::cout << std::setprecision( 10 );
	for ( int j=0; j<ids.Size(); j++ )
		std::cout << " Psi at (" << points( 0, j ) << ", " << points( 1, j ) << ") = " << u_solution.GetValue( ids[ j ], ips[ j ] ) << std::endl;

	// Save the output
	{

		ofstream mesh_ofs( options.at( "OutputMeshFile" ).as_string() );
		mesh_ofs.precision(8);
		mesh->Print(mesh_ofs);

		ofstream q_solution_ofs( options.at( "GradPsiFile" ).as_string() );
		q_solution_ofs.precision(8);
		q_solution.Save(q_solution_ofs);

		ofstream u_solution_ofs( options.at( "PsiFile" ).as_string() );
		u_solution_ofs.precision(8);
		u_solution.Save(u_solution_ofs);

	}

	// Free the used memory.
	delete mesh;

	return 0;

}

