# Positions and lengths in physical space are specified in metres, relative to the symmetry axis for R, and the Z=0 plane for Z
# Currents are current densities in MA/m^2
# For typical numbers, copper coils can achieve 5 MA/m^2
# and superconducting Nb3Sn coil packs average 20 MA/m^2

[options]

# will generate vacuum.mesh, vacuum_psi.gf, vacuum_grad_psi.gf
FilePrefix = "vacuum"

# Details of the solution domain
[domain]

# Boundaries of the domain
RMin = 0.05
RMax = 1.5
ZMin = -1.5
ZMax = 1.5

# Don't touch this
BoundaryCondition = "VonHagenow"

# Away from the coils, what is a reasonable guess at the 
# scale of psi variation. Used to generate initial mesh. 
# Refined Later.
PsiResolution = 0.25

# Coils is an array of tables
# just keep adding coil packs by adding entries.

[[coils]]
R = 1
Z = 1
Width = 0.1
Height = 0.1
Current = 25

[[coils]]
R = 1
Z = -1
Width = 0.1
Height = 0.1
Current = 25


