# Positions and lengths in physical space are specified in metres, relative to the symmetry axis for R, and the Z=0 plane for Z
# Currents are in MA
# For typical numbers, copper coils can achieve 5 MA/m^2
# and superconducting Nb3Sn coil packs average 20 MA/m^2

[options]

MeshFile = "MRI_Mesh.vtk"
FinalMeshFile = "output_mri.vtk"
PsiFile = "mri_psi.gf"
GradPsiFile = "mri_grad_psi.gf"
NetCDFFile = "MRIModel.nc"

# Details of the solution domain
[domain]

# Boundaries of the domain
RMin = 0.05
RMax = 1.0
ZMin = -1.6
ZMax = 1.6

# Don't touch this
BoundaryCondition = "VonHagenow"

# Away from the coils, what is a reasonable guess at the 
# scale of psi variation. Used to generate initial mesh. 
# Refined Later.
CellSize = 0.1


VacuumVessel = [
	[-1.6,0.05],
	[-1.6,1.0 ],
	[ 1.6,1.0 ],
	[ 1.6,0.05],
]

# Coils is an array of tables
# just keep adding coils by adding entries.

[[coils]]
R = 0.488
Z = 0.0875
Width = 0.03
Height = 0.14
Current = 0.552900

[[coils]]
R = 0.4905
Z = 0.2855
Width = 0.035
Height = 0.155
Current = 0.9215

[[coils]]
R = 0.503
Z = 0.62
Width = 0.04
Height = 0.24
Current = 1.8624

[[coils]]
R = 0.8505
Z = 0.488
Width = 0.035
Height = 0.158
Current = -1.09998

[[coils]]
R = 0.488
Z = -0.0875
Width = 0.03
Height = 0.14
Current = 0.552900

[[coils]]
R = 0.4905
Z = -0.2855
Width = 0.035
Height = 0.155
Current = 0.9215

[[coils]]
R = 0.503
Z = -0.62
Width = 0.04
Height = 0.24
Current = 1.8624

[[coils]]
R = 0.8505
Z = -0.488
Width = 0.035
Height = 0.158
Current = -1.09998
