# Test configuration for Soloviev Equilibrium

[options]

# will generate vacuum.vtk, vacuum_psi.gf, vacuum_grad_psi.gf
MeshFile = "vacuum.vtk"
OutputMeshFile = "output_vacuum.vtk"
PsiFile = "vacuum_psi.gf"
GradPsiFile = "vacuum_grad_psi.gf"

# Details of the solution domain
[domain]

# Boundaries of the domain
RMin = 1
RMax = 2.5
ZMin = -3.0
ZMax = 3.0

# Don't touch this
BoundaryCondition = "Exact"

# Away from the coils, what is a reasonable guess at the 
# scale of psi variation. Used to generate initial mesh. 
# Refined Later.
PsiResolution = 0.5

# If this section is absent, no toroidal field is used
[ToroidalField]

# Provide II' as a profile in the plasma region
ToroidalFieldProfile = "tf_soloviev.dat"
ToroidalFieldDataType = "HermiteSplineData"



# Defines the plasma region and its profiles
[Plasma]

# Set both PlasmaPsiMin and PlasmaPsiMax to 
# have upper and lower bounds on the plasma domain
# if either is not set, then the default is +/- Inf
# e.g. for the plasma to occupy all psi values below 0, set
# only PlasmaPsiMax = 0. PlasmaPsiMin will be inferred to be -∞ so
# the plasma region is -∞ < psi <= 0.
# Setting neither Min nor Max will set the plasma to occupy the whole domain.
PlasmaPsiMin = 
PlasmaPsiMax = 

# Include rotation?
Rotation = false
RotationProfile = ""
# Do we compute phi_0 ourselves?
ComputePhi0 = false

# Can be MHD or GK
KineticData = "MHD"

# For MHD (i.e. single fluid, massless electrons) equilibria
# without rotation, we only need P'
# with rotation, we need P, T (in addition to Omega(psi))
[plasma.MHD]
# if Rotation == false, set PPrimeProfile to be P' in the plasma region.
PPrimeProfile = "pprime_soloviev.dat"
PPrimeProfileDataType = "HermiteSplineData"



