# Positions and lengths in physical space are specified in metres, relative to the symmetry axis for R, and the Z=0 plane for Z
# Currents are in MA
# For typical numbers, copper coils can achieve 5 MA/m^2
# and superconducting Nb3Sn coil packs average 20 MA/m^2

[options]

MeshFile = "vactest.vtk"
FinalMeshFile = "output_vactest.vtk"
PsiFile = "vactest_psi.gf"
GradPsiFile = "vactest_grad_psi.gf"
NetCDFFile = "vactest.nc"

# Details of the solution domain
[domain]

# Boundaries of the domain
RMin = 0.05
RMax = 1.5
ZMin = -1.5
ZMax = 1.5

# Don't touch this
BoundaryCondition = "VonHagenow"

# Away from the coils, what is a reasonable guess at the 
# scale of psi variation. Used to generate initial mesh. 
# Refined Later.
CellSize = 0.1


VacuumVessel = [
	[-1.5,0.05],
	[-1.5,1.0 ],
	[ 1.5,1.0 ],
	[ 1.5,0.05],
]

# Coils is an array of tables
# just keep adding coils by adding entries.

[[coils]]
R = 1.2
Z = 0.0
Width = 0.025
Height = 0.025
Current = 1.0


