# Positions and lengths in physical space are specified in metres, relative to the symmetry axis for R, and the Z=0 plane for Z
# Currents are in MA
# For typical numbers, copper coils can achieve 5 MA/m^2
# and superconducting Nb3Sn coil packs average 20 MA/m^2

[options]

# will generate vacuum.vtk, vacuum_psi.gf, vacuum_grad_psi.gf
MeshFile = "helmholtz.vtk"
OutputMeshFile = "output_helmholtz.vtk"
PsiFile = "helmholtz_psi.gf"
GradPsiFile = "helmholtz_grad_psi.gf"

# Details of the solution domain
[domain]

# Boundaries of the domain
RMin = 0.0
RMax = 2.5
ZMin = -1.5
ZMax = 1.5

# Don't touch this
BoundaryCondition = "VonHagenow"

# Away from the coils, what is a reasonable guess at the 
# scale of psi variation. Used to generate initial mesh. 
# Refined Later.
PsiResolution = 0.1

# Helmholtz coil, with approxmiately-point coils
[[coils]]
R = 2.0
Z = 1.0
Width = 0.01
Height = 0.01
Current = 1.0

[[coils]]
R = 2.0
Z = -1.0
Width = 0.01
Height = 0.01
Current = 1.0
